FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt
RUN apt-get update && apt-get install -y cron procps && rm -rf /var/lib/apt/lists/*

COPY models_backup.py /app/models_backup.py
COPY crontab.txt /etc/cron.d/backup-cron

RUN chmod 0644 /etc/cron.d/backup-cron && crontab /etc/cron.d/backup-cron

RUN touch /var/log/cron.log

CMD ["python", "/app/models_backup.py"]

CMD python /app/models_backup.py && cron && tail -f /var/log/cron.log

